/**
 * File: lib/rbac/permissions.ts
 * Module: rbac
 * Purpose: Define RBAC permission catalog and role defaults.
 * Author: StockTrade
 * Last-updated: 2026-04-01
 * Notes:
 * - Keep permission keys stable to avoid breaking stored configs.
 * - Update DEFAULT_ROLE_PERMISSIONS when adding new keys.
 */

export const ROLE_KEYS = ["USER", "MODERATOR", "ADMIN", "SUPER_ADMIN"] as const
export type RoleKey = (typeof ROLE_KEYS)[number]

export type PermissionRisk = "low" | "medium" | "high"

export interface PermissionDefinition {
  key: string
  label: string
  description: string
  category: string
  risk: PermissionRisk
}

export const PERMISSIONS = [
  {
    key: "admin.all",
    label: "Admin Full Access",
    description: "Full administrative access across the platform.",
    category: "ACCESS_CONTROL",
    risk: "high",
  },
  {
    key: "admin.access-control.view",
    label: "Access Control View",
    description: "View role permissions and access control settings.",
    category: "ACCESS_CONTROL",
    risk: "medium",
  },
  {
    key: "admin.access-control.manage",
    label: "Access Control Manage",
    description: "Modify role permissions and access control policies.",
    category: "ACCESS_CONTROL",
    risk: "high",
  },
  {
    key: "admin.profile.read",
    label: "Admin Profile Read",
    description: "View own admin profile details.",
    category: "PROFILE",
    risk: "low",
  },
  {
    key: "admin.profile.manage",
    label: "Admin Profile Manage",
    description: "Update own admin profile details.",
    category: "PROFILE",
    risk: "low",
  },
  {
    key: "admin.users.read",
    label: "Users Read",
    description: "View user lists, profiles, and activity summaries.",
    category: "USERS",
    risk: "medium",
  },
  {
    key: "admin.users.manage",
    label: "Users Manage",
    description: "Create, update, activate, or deactivate users.",
    category: "USERS",
    risk: "high",
  },
  {
    key: "admin.users.credentials",
    label: "Users Credentials",
    description: "Reset passwords and MPIN for users.",
    category: "USERS",
    risk: "high",
  },
  {
    key: "admin.users.kyc",
    label: "Users KYC",
    description: "Review and approve/reject KYC applications.",
    category: "USERS",
    risk: "high",
  },
  {
    key: "admin.users.crm",
    label: "Users CRM",
    description: "Notes, callback tasks, and follow-ups on client records (KYC drawer).",
    category: "USERS",
    risk: "medium",
  },
  {
    key: "admin.users.risk",
    label: "Users Risk",
    description: "View or update user risk limits and alerts.",
    category: "USERS",
    risk: "high",
  },
  {
    key: "admin.users.rm",
    label: "Users RM Assignment",
    description:
      "Assign or manage relationship managers for users, including the client RM assignment request queue.",
    category: "USERS",
    risk: "medium",
  },
  {
    key: "admin.users.bank.sensitive",
    label: "Users Bank Sensitive",
    description:
      "View full bank account numbers and IFSC for payouts when combined with funds access (audited).",
    category: "USERS",
    risk: "high",
  },
  {
    key: "admin.funds.read",
    label: "Funds Read",
    description: "View deposits, withdrawals, and transactions.",
    category: "FUNDS",
    risk: "medium",
  },
  {
    key: "admin.funds.manage",
    label: "Funds Manage",
    description: "Approve, reject, or adjust user funds.",
    category: "FUNDS",
    risk: "high",
  },
  {
    key: "admin.funds.override",
    label: "Funds Override",
    description: "Perform direct trading account fund overrides.",
    category: "FUNDS",
    risk: "high",
  },
  {
    key: "admin.deposits.manage",
    label: "Deposits Manage",
    description: "Approve or reject deposit requests.",
    category: "FUNDS",
    risk: "high",
  },
  {
    key: "admin.withdrawals.manage",
    label: "Withdrawals Manage",
    description: "Approve or reject withdrawal requests.",
    category: "FUNDS",
    risk: "high",
  },
  {
    key: "admin.withdrawals.review",
    label: "Withdrawals Review",
    description:
      "View the risk-aware withdrawal queue, risk scores, and hold history.",
    category: "FUNDS",
    risk: "low",
  },
  {
    key: "admin.withdrawals.rules",
    label: "Withdrawals Risk Rules",
    description:
      "Create / edit / disable rules used by the withdrawal risk-score engine.",
    category: "FUNDS",
    risk: "high",
  },
  {
    key: "admin.surveillance.read",
    label: "Surveillance Read",
    description:
      "View the internal-fraud surveillance queue (HEAVY_HITTER, SUSPICIOUS_WINNER, MULTI_ACCOUNT, BONUS_ABUSE).",
    category: "RISK",
    risk: "low",
  },
  {
    key: "admin.surveillance.manage",
    label: "Surveillance Manage",
    description:
      "Assign, dismiss, or resolve surveillance alerts. Does not mutate winner-control or bonus-grant state.",
    category: "RISK",
    risk: "high",
  },
  {
    key: "admin.surveillance.rules",
    label: "Surveillance Rules",
    description:
      "Create / edit / disable surveillance rules. Tuning is sacred — alerts always snapshot params at fire-time.",
    category: "RISK",
    risk: "high",
  },
  {
    key: "admin.orders.read",
    label: "Orders Read",
    description: "View orders and related trading activity.",
    category: "TRADING",
    risk: "medium",
  },
  {
    key: "admin.orders.manage",
    label: "Orders Manage",
    description: "Modify order status or trading details.",
    category: "TRADING",
    risk: "high",
  },
  {
    key: "admin.positions.read",
    label: "Positions Read",
    description: "View positions and exposure details.",
    category: "TRADING",
    risk: "medium",
  },
  {
    key: "admin.positions.manage",
    label: "Positions Manage",
    description: "Modify positions or execute admin trades.",
    category: "TRADING",
    risk: "high",
  },
  {
    key: "admin.activity.read",
    label: "Activity Read",
    description: "View system and user activity feeds.",
    category: "ANALYTICS",
    risk: "medium",
  },
  {
    key: "admin.charts.read",
    label: "Charts Read",
    description: "View chart-based analytics and trends.",
    category: "ANALYTICS",
    risk: "low",
  },
  {
    key: "admin.top-traders.read",
    label: "Top Traders Read",
    description: "View top trader and leaderboard data.",
    category: "ANALYTICS",
    risk: "low",
  },
  {
    key: "admin.analytics.read",
    label: "Analytics Read",
    description: "View analytics dashboards and KPIs.",
    category: "ANALYTICS",
    risk: "low",
  },
  {
    key: "admin.stats.read",
    label: "Stats Read",
    description: "View platform statistics.",
    category: "ANALYTICS",
    risk: "low",
  },
  {
    key: "admin.reports.read",
    label: "Reports Read",
    description: "View financial and compliance reports.",
    category: "ANALYTICS",
    risk: "medium",
  },
  {
    key: "admin.audit.read",
    label: "Audit Read",
    description: "View audit trail entries.",
    category: "ANALYTICS",
    risk: "medium",
  },
  {
    key: "admin.session-security.read",
    label: "Session Security Read",
    description: "View active sessions, device registry, and security incidents.",
    category: "SECURITY",
    risk: "medium",
  },
  {
    key: "admin.session-security.manage",
    label: "Session Security Manage",
    description: "Revoke sessions, update session policy, resolve security incidents.",
    category: "SECURITY",
    risk: "high",
  },
  {
    key: "admin.logs.read",
    label: "Logs Read",
    description: "View system logs and diagnostics.",
    category: "ANALYTICS",
    risk: "medium",
  },
  {
    key: "admin.risk.read",
    label: "Risk Read",
    description: "View risk configurations and alerts.",
    category: "RISK",
    risk: "medium",
  },
  {
    key: "admin.risk.manage",
    label: "Risk Manage",
    description: "Manage risk limits, alerts, and configurations.",
    category: "RISK",
    risk: "high",
  },
  {
    key: "admin.system.read",
    label: "System Health Read",
    description: "View system health and performance metrics.",
    category: "SYSTEM",
    risk: "medium",
  },
  {
    key: "admin.settings.manage",
    label: "Settings Manage",
    description: "Manage platform settings and configuration.",
    category: "SYSTEM",
    risk: "high",
  },
  {
    key: "admin.notifications.manage",
    label: "Notifications Manage",
    description: "Create and manage platform notifications.",
    category: "SYSTEM",
    risk: "medium",
  },
  {
    key: "admin.referrals.read",
    label: "Referrals Read",
    description: "View referral attributions, rewards, and program configuration.",
    category: "USERS",
    risk: "medium",
  },
  {
    key: "admin.referrals.manage",
    label: "Referrals Manage",
    description: "Edit referral milestone rules and program settings.",
    category: "USERS",
    risk: "high",
  },
  {
    key: "admin.upload.manage",
    label: "Uploads Manage",
    description: "Upload and manage admin assets.",
    category: "SYSTEM",
    risk: "medium",
  },
  {
    key: "admin.cleanup.read",
    label: "Cleanup Read",
    description: "Preview cleanup operations.",
    category: "SYSTEM",
    risk: "high",
  },
  {
    key: "admin.cleanup.execute",
    label: "Cleanup Execute",
    description: "Execute cleanup operations.",
    category: "SYSTEM",
    risk: "high",
  },
  {
    key: "admin.queue.read",
    label: "Queue Read",
    description: "View queue and batcher status.",
    category: "SYSTEM",
    risk: "low",
  },
  {
    key: "admin.terminal.shell",
    label: "Admin Live Terminal",
    description:
      "Open a real browser PTY session via terminal-gateway (full shell on gateway host; SUPER_ADMIN only).",
    category: "SYSTEM",
    risk: "high",
  },
  {
    key: "admin.super.financial.read",
    label: "Super Admin Financial Read",
    description: "Access super-admin financial endpoints.",
    category: "SUPER_ADMIN",
    risk: "high",
  },
  {
    key: "admin.super.financial.manage",
    label: "Super Admin Financial Manage",
    description: "Update super-admin financial configuration and rules.",
    category: "SUPER_ADMIN",
    risk: "high",
  },
  {
    key: "admin.segments.read",
    label: "Segments Read",
    description: "View user segments and their members.",
    category: "USERS",
    risk: "low",
  },
  {
    key: "admin.segments.manage",
    label: "Segments Manage",
    description: "Create, edit, and delete user segments; add/remove members.",
    category: "USERS",
    risk: "medium",
  },
  {
    key: "admin.policies.read",
    label: "Policies Read",
    description: "View trading policies and their rules.",
    category: "RISK",
    risk: "low",
  },
  {
    key: "admin.policies.manage",
    label: "Policies Manage",
    description: "Create, edit, and delete trading policies; assign to segments.",
    category: "RISK",
    risk: "high",
  },
  {
    key: "admin.house.read",
    label: "House Book Read",
    description:
      "View the broker's counterparty book — net house P&L, exposure heatmap, concentration risk, scenario VaR.",
    category: "HOUSE",
    risk: "high",
  },
  {
    key: "admin.house.winner",
    label: "House Winner Mitigation",
    description:
      "Manage Winner Mitigation Engine: per-client spread multiplier, position cap, instrument blocks, close-only / close-out (B-book restriction ladder).",
    category: "HOUSE",
    risk: "high",
  },
  {
    key: "admin.house.spread",
    label: "House Spread Manage",
    description: "Manage spread / markup configuration per instrument · segment · client tier.",
    category: "HOUSE",
    risk: "high",
  },
  {
    key: "admin.house.risk",
    label: "House Risk Manage",
    description:
      "Manage house-level risk caps (per-segment, per-symbol, max-loss-per-day circuit breakers, manual halts).",
    category: "HOUSE",
    risk: "high",
  },
  {
    key: "admin.house.adjust",
    label: "House Trade Adjust",
    description: "Manually reject / requote / void trades; force margin call; force liquidation.",
    category: "HOUSE",
    risk: "high",
  },
  {
    key: "admin.bonus.read",
    label: "Bonus Read",
    description: "View bonus rules, grants, promo codes, and per-client credit ledger.",
    category: "BONUS",
    risk: "low",
  },
  {
    key: "admin.bonus.manage",
    label: "Bonus Manage",
    description: "Create / edit bonus rules, issue grants, manage promo codes, manual clawback.",
    category: "BONUS",
    risk: "high",
  },
  {
    key: "admin.bonus.bulk",
    label: "Bonus Bulk Issue",
    description: "Bulk-issue grants across many clients (campaign-style). Restricted.",
    category: "BONUS",
    risk: "high",
  },
  // Phase 11 — Affiliate / IB program
  {
    key: "admin.affiliate.read",
    label: "Affiliate Read",
    description: "View affiliate roster, commissions ledger, attribution map, payout queue.",
    category: "AFFILIATE",
    risk: "low",
  },
  {
    key: "admin.affiliate.manage",
    label: "Affiliate Manage",
    description: "Create / edit affiliates, set commission rules, change tier, manual re-attribution.",
    category: "AFFILIATE",
    risk: "high",
  },
  {
    key: "admin.affiliate.payout",
    label: "Affiliate Payout",
    description: "Approve / mark-paid / cancel affiliate payouts. Sets TDS rate per payout (legal review required before production).",
    category: "AFFILIATE",
    risk: "high",
  },
  // Phase 12 — Communications engine
  {
    key: "admin.comms.read",
    label: "Comms Read",
    description: "View comms templates, campaigns, message feed, consent ledger. No send privileges.",
    category: "COMMS",
    risk: "low",
  },
  {
    key: "admin.comms.send",
    label: "Comms Send (single)",
    description: "Send ad-hoc single-recipient messages from Client 360 (WhatsApp/SMS/Email/Voice). Subject to consent + DLT gates.",
    category: "COMMS",
    risk: "medium",
  },
  {
    key: "admin.comms.bulk",
    label: "Comms Bulk / Campaign",
    description: "Create + run drip / one-shot campaigns over the audience. Highest blast radius; requires two-person review at production rollout.",
    category: "COMMS",
    risk: "high",
  },
] as const satisfies readonly PermissionDefinition[]

export type PermissionKey = (typeof PERMISSIONS)[number]["key"]

export const DEFAULT_ROLE_PERMISSIONS: Record<RoleKey, PermissionKey[]> = {
  USER: [],
  MODERATOR: [
    "admin.profile.read",
    "admin.profile.manage",
    "admin.users.read",
    "admin.users.kyc",
    "admin.users.crm",
    "admin.activity.read",
    "admin.orders.read",
    "admin.positions.read",
    "admin.charts.read",
    "admin.top-traders.read",
    "admin.analytics.read",
    "admin.stats.read",
  ],
  ADMIN: [
    "admin.access-control.view",
    "admin.profile.read",
    "admin.profile.manage",
    "admin.users.read",
    "admin.users.manage",
    "admin.users.credentials",
    "admin.users.kyc",
    "admin.users.crm",
    "admin.users.risk",
    "admin.users.rm",
    "admin.funds.read",
    "admin.funds.manage",
    "admin.deposits.manage",
    "admin.withdrawals.manage",
    "admin.withdrawals.review",
    "admin.orders.read",
    "admin.positions.read",
    "admin.activity.read",
    "admin.charts.read",
    "admin.top-traders.read",
    "admin.analytics.read",
    "admin.stats.read",
    "admin.reports.read",
    "admin.audit.read",
    "admin.session-security.read",
    "admin.session-security.manage",
    "admin.logs.read",
    "admin.risk.read",
    "admin.risk.manage",
    "admin.system.read",
    "admin.settings.manage",
    "admin.notifications.manage",
    "admin.referrals.read",
    "admin.referrals.manage",
    "admin.upload.manage",
    "admin.cleanup.read",
    "admin.cleanup.execute",
    "admin.queue.read",
    "admin.segments.read",
    "admin.segments.manage",
    "admin.policies.read",
    "admin.policies.manage",
    "admin.house.read",
    "admin.bonus.read",
    "admin.bonus.manage",
    "admin.affiliate.read",
    "admin.affiliate.manage",
    "admin.comms.read",
    "admin.comms.send",
    "admin.surveillance.read",
    "admin.surveillance.manage",
  ],
  SUPER_ADMIN: [
    "admin.all",
    "admin.access-control.manage",
    "admin.super.financial.read",
    "admin.super.financial.manage",
    "admin.funds.override",
    "admin.house.read",
    "admin.house.winner",
    "admin.house.spread",
    "admin.house.risk",
    "admin.house.adjust",
    "admin.bonus.read",
    "admin.bonus.manage",
    "admin.bonus.bulk",
    "admin.affiliate.read",
    "admin.affiliate.manage",
    "admin.affiliate.payout",
    "admin.comms.read",
    "admin.comms.send",
    "admin.comms.bulk",
    "admin.withdrawals.review",
    "admin.withdrawals.rules",
    "admin.surveillance.read",
    "admin.surveillance.manage",
    "admin.surveillance.rules",
  ],
}

export const RESTRICTED_PERMISSIONS: Partial<Record<PermissionKey, RoleKey[]>> = {
  "admin.all": ["SUPER_ADMIN"],
  "admin.access-control.manage": ["SUPER_ADMIN"],
  "admin.terminal.shell": ["SUPER_ADMIN"],
  "admin.super.financial.read": ["SUPER_ADMIN"],
  "admin.super.financial.manage": ["SUPER_ADMIN"],
  "admin.funds.override": ["SUPER_ADMIN"],
  "admin.users.bank.sensitive": ["SUPER_ADMIN", "ADMIN"],
  "admin.surveillance.rules": ["SUPER_ADMIN"],
}

